# Generated by Django 3.2.16 on 2023-01-06 17:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viscometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('serial_number', models.CharField(max_length=20)),
                ('constant', models.DecimalField(decimal_places=7, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('type', models.IntegerField(choices=[(0, 'Suspended Flow Viscometer'), (1, 'Reverse Flow Viscometer')])),
                ('calibration_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'ordering': ['type', 'size'],
            },
        ),
    ]
